### ISSUE TITLE
Please publish to Maven repository

### ISSUE THREAD

**Issue by ZsZs** [sbellus/fitnesse-plantuml-plugin#1]
Hi,

I'm launching FitNesse from Maven Plugin: https://github.com/ZsZs/FitNesseLauncher and I'd like to configure jar as a dependency in pom.

I think to publish to Maven repo makes sense anyway.

Thank you,
Zsolt

**Comment by sbellus** [comment]
Hi

I am cpp developer.
Please can you give me some hints how to publish to maven repo?

Typed with thumbs.

**Comment by sbellus** [comment]
Somebody already did it
https://mvnrepository.com/artifact/com.processpuzzle.fitnesse/fitnesse-plantuml-plugin
